language: ko

reviews:
  enabled: true
  review_comment_type: suggestion
  request_changes: true
  max_comments: 70

include:
  - "src/**"
  - "pages/**"
  - "components/**"
  - "lib/**"
  - "hooks/**"

exclude:
  - "**/*.md"
  - "node_modules/**"
  - ".next/**"
  - "dist/**"
  - "coverage/**"

rules:
  - name: Next.js (Pages Router) Best Practices
    description: |
      Next.js Pages Router 기반 구조의 규칙을 검토합니다.
      - getServerSideProps / getStaticProps 사용 적절성
      - getInitialProps 비추천 여부 확인
      - pages 디렉토리 라우팅 컨벤션 점검
      - next/image 사용 여부
    priority: P0

  - name: TypeScript Strictness
    description: |
      타입 안정성, any 남용 여부, 타입 추론 가능 부분, 인터페이스/타입 정의 적절성 등을 검토합니다.
      불필요한 optional 체이닝, null 체크 누락, 타입 좁히기 가능성 등을 확인합니다.
    priority: P0

  - name: React Hooks & Component Quality
    description: |
      React 컴포넌트의 상태 관리와 훅 사용을 점검합니다.
      - useEffect 의존성 정확성
      - useCallback/useMemo 최적화 적절성
      - 불필요한 re-render 발생 여부
      - props drilling 심한 경우 경고
    priority: P1

  - name: TailwindCSS Review
    description: |
      TailwindCSS 클래스의 중복, 비효율적 구조, 불필요하게 긴 클래스 조합 등을 점검합니다.
      - shadcn 구성 요소와 tailwind utility 조합 시 충돌 여부
      - className 난잡하게 나열된 부분 개선 제안
    priority: P1

  - name: shadcn/ui Best Practices
    description: |
      shadcn/ui 구성 요소 사용이 적절한지 검토합니다.
      - 불필요한 custom component 중복 여부
      - 기존 shadcn 컴포넌트로 대체 가능 여부
      - 구성 요소 props 사용 최적화
    priority: P1

  - name: Performance & Code Cleanliness
    description: |
      코드 유지 보수성과 렌더링 성능을 중심으로 확인합니다.
      - Next.js 번들 사이즈 최적화
      - dynamic import 추천
      - 중복 함수/컴포넌트 제거
      - 파일 구조 컨벤션 점검
    priority: P2
